/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32f4xx_gpio.h"

volatile bool is_btn_triggered = false; 

int main(void)
{
    GPIOA_PERI_CLK_EN();
    GPIOC_PERI_CLK_EN();
    SYSCFG_PERI_CLK_EN();

    st_gpio_t btn = {GPIO_C, GPIO13};
    st_gpio_config_mode(GPIOA, GPIO5, OUTPUT);
    st_gpio_config_mode(GPIOC, btn.pin, INPUT);

    st_gpio_config_interrupt(&btn, GPIO_INTR_RISE_EDGE);
    NVIC_EnableIRQ(EXTI15_10_IRQn);
    NVIC_SetPriority(EXTI15_10_IRQn, 1);

    while (true) {
        if (is_btn_triggered) {
            st_gpio_toggle_pin(GPIOA, GPIO5);
            is_btn_triggered = false;
        }
    }
}

void EXTI15_10_IRQHandler(void)
{
    is_btn_triggered = true;
    EXTI->PR |= (1 << 13);
}