/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_gpio.h"

int main(void)
{
    GPIOA_PERI_CLK_EN();
    st_gpio_config_mode(GPIOA, GPIO5, OUTPUT);

    while (1) {
        st_gpio_toggle_pin(GPIOA, GPIO5);
        for (int i=0; i<0xFFFFF; i++);
    }
}