/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <string.h>
#include "stm32f4xx_debug.h"

int main(void)
{
    st_debug_init();
    char message[5];
    // uint8_t a = 10;
    st_usart_receive_data_blocking(USART_2, (uint8_t*)message, 5);
    while (1) {
        LOG_INFO("message:%s", message);
    }
    return 0;
}